[package]
name = "kvm"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false

[dependencies]
error-chain = "0.11"
nix = "0.9"
libc = "0.2"
vm-x86 = { path = "../../arches/x86" }
