[package]
name = "kvm"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false

[dependencies]
error-chain = "0.11"
accel = { path = "../accel" }
kvm-sys = { path = "kvm-sys" }
vm-x86 = { path = "../../arches/x86" }
memmap = "0.5"
