[package]
name = "vm"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]

[dependencies]
x86 = { path = "arches/x86", optional = true }

env_logger = "*"

[features]
default = [
]

[workspace]
