[package]
name = "vm"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]

[dependencies]
vm-x86 = { path = "arches/x86" }
accel = { path = "vmm/accel" }
kvm = { path = "vmm/kvm" }

[workspace]
