[package]
name = "hax"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false

[dependencies]
error-chain = "0.11"
accel = { path = "../accel" }
vm-x86 = { path = "../../arches/x86" }
hax-sys = { path = "hax-sys" }
