[package]
name = "kvm-sys"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false

[dependencies]
nix = "0.9"
bitflags = "1"
vm-x86 = { path = "../../../arches/x86/" }
